### ISSUE TITLE
Bad Russian and maybe other languages

### ISSUE THREAD

**Issue by WhO2022** [basharast/wut#21]
Hello, i set Russian language and translated not all objects, and bad translations

**Comment by basharast** [comment]
Hi :),
This is automatic translation by Google and most of it not accurate, 
the main idea to make base translation so others can help to fix it,

if you wish to fix it then:
- After extracting the package got to `Translations` folder
- Read `Important.txt`
- At `Translations\Languages` there is folder `ru-RU`
- Inside `ru-RU` there is file called `Resources.resw` 
- Use any text editor to open it (preferred [Notepad++](https://notepad-plus-plus.org/))
- Fix it and share it here anytime

if you wasn't able to locate that file then just download it from below
[Resources.zip](https://github.com/basharast/wut/files/15332103/Resources.zip)

Ensure you are fixing only the value between (as in the picture)
```xml
<value>translate text</value>
```
![photo_2024-01-02_04-35-34](https://github.com/basharast/wut/assets/3244951/98999c1a-021e-45be-8c32-e4c6854ef802)


Since I added the multi languages support years ago, I asked a lot for everyone to help to fix those translations.
only got help for Chinese and Vietnamese nothing else.
